name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.9
    - run: make page
    - run: touch page/__site/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: page/__site
